export { default as WhyGammaLexSection } from './WhyGammaLexSection'
export { default as ProblemsWeSolveSection } from './ProblemsWeSolveSection'
export { default as HowGammaLexWorksSection } from './HowGammaLexWorksSection'
export { default as ImpactSection } from './ImpactSection'
export { default as RevenueOptimizationSection } from './RevenueOptimizationSection'
export { default as AIApplicationsSection } from './AIApplicationsSection'